// login types
export const LOGIN = 'LOGIN';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// signup types
export const SIGNUP = 'SIGNUP';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//user data types
export const USER_DATA = 'USER_DATA';
export const USER_DATA_FAILURE = 'USER_DATA_FAILURE';

//forgot password types
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//get user profile types
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

//client types
export const CLIENT_DATA = "CLIENT_DATA"
export const CLIENT_DATA_FAILURE = "CLIENT_DATA_FAILURE"

// workplace
export const WORKPLACE_DATA = "WORKPLACE_DATA"
export const WORKPLACE_DATA_FAILURE = "WORKPLACE_DATA_FAILURE"
export const CREATE_WORKPLACE = "CREATE_WORKPLACE"
export const CREATE_WORKPLACE_FAILURE = "CREATE_WORKPLACE_FAILURE"
export const GET_INDIVIDUAL_WORKPLACE_SUCCES = "GET_INDIVIDUAL_WORKPLACE_SUCCESS"
export const GET_INDIVIDUAL_WORKPLACE_FAILURE = "GET_INDIVIDUAL_WORKPLACE_FAILURE"
export const UPDATE_WORKPLACE = "UPDATE_WORKPLACE"
export const UPDATE_WORKPLACE_FAILURE = "UPDATE_WORKPLACE_FAILURE"
export const REMOVE_WORKPLACE="REMOVE_WORKPLACE"
export const REMOVE_WORKPLACE_FAILURE = "REMOVE_WORKPLACE_FAILURE"

//client
export const CLIENT_BY_ID = "CLIENT_BY_ID"
export const CLIENT_BY_ID_FAILURE = "CLIENT_BY_ID_FAILURE"

//Services
export const SERVICES_DATA = "SERVICES_DATA"
export const SERVICES__DATA_FAILURE = "SERVICES_DATA_FAILURE"
export const CREATE_SERVICES = "CREATE_SERVICES"
export const CREATE_SERVICES_FAILURE = "CREATE_SERVICES_FAILURE"
export const GET_INDIVIDUAL_SERVICE_SUCCESS = "GET_INDIVIDUAL_SERVICE_SUCCESS"
export const GET_INDIVIDUAL_SERVICE_FAILURE = "GET_INDIVIDUAL_SERVICE_FAILURE"
export const UPDATE_SERVICES = "UPDATE_SERVICES"
export const UPDATE_SERVICES_FAILURE = "UPDATE_SERVICES_FAILURE"
export const REMOVE_SERVICES="REMOVE_SERVICES"
export const REMOVE_SERVICES_FAILURE = "REMOVE_SERVICES_FAILURE"

//Secreataries
export const SECRETARIES_DATA = "SECRETARIES_DATA"
export const SECRETARIES_DATA_FAILURE = "SECRETARIES_DATA_FAILURE"
export const CREATE_SECRETARIES = "CREATE_SECRETARIES"
export const CREATE_SECRETARIES_FAILURE = "CREATE_SECRETARIES_FAILURE"
export const GET_INDIVIDUAL_SECRETARIES_SUCCESS= "GET_INDIVIDUAL_SECRETARIES_SUCCESS"
export const GET_INDIVIDUAL_SECRETARIES_FAILURE = "GET_INDIVIDUAL_SECRETARIES_FAILURE"
export const UPDATE_SECRETARIES = "UPDATE_SECRETARIES"
export const UPDATE_SECRETARIES_FAILURE = "UPDATE_SECRETARIES_FAILURE"
export const REMOVE_SECRETARIES="REMOVE_SECRETARIES"
export const REMOVE_SECRETARIES_FAILURE = "REMOVE_SECRETARIES_FAILURE"

//Schedule
export const SCHEDULE_DATA = "SCHEDULE_DATA"
export const SCHEDULE_DATA_FAILURE = "SCHEDULE_DATA_FAILURE"
export const CREATE_SCHEDULE = "CREATE_SCHEDULE"
export const CREATE_SCHEDULE_FAILURE = "CREATE_SCHEDULE_FAILURE"

//ScheduleAppointment
export const APPOINTMENT_DATA = "APPOINTMENT_DATA"
export const APPOINTMENT_DATA_FAILURE = "APPOINTMENT_DATA_FAILURE"
export const CREATE_APPOINTMENT_DATA = "CREATE_APPOINTMENT_DATA"
export const CREATE_APPOINTMENT_DATA_FAILURE = "CREATE_APPOINTMENT_DATA_FAILURE"
